---
- name: Install Java, Git, and Docker on servers; Maven on Jenkins
  hosts: servers:jenkins
  become: yes
  tasks:
    - name: Install Java 17 on Amazon Linux
      when: "'amazon' in ansible_distribution.lower()"
      yum:
        name: java-17-amazon-corretto-devel
        state: present

    - name: Install OpenJDK 17 on Ubuntu
      when: "'ubuntu' in ansible_distribution.lower()"
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Git
      package:
        name: git
        state: present

    - name: Install Docker on Amazon Linux
      when: "'amazon' in ansible_distribution.lower()"
      yum:
        name: docker
        state: present

    - name: Install Docker on Ubuntu
      when: "'ubuntu' in ansible_distribution.lower()"
      apt:
        name: docker.io
        state: present

    - name: Install Maven
      package:
        name: maven
        state: present
