- name: Install Java, Git, Docker and Python on servers, and Maven on Jenkins
  hosts: servers:jenkins
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Install Java 17
      yum:
        name: java-17-amazon-corretto-devel
        state: present

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Install Python pip
      yum:
        name: python37
        state: present 

    - name: Install Maven
      yum:
        name: maven
        state: present
