---
- name: Install Java, Git, and Docker on servers; Maven on Jenkins
  hosts: servers:jenkins
  become: yes
  tasks:
    - name: Install Java 17
      package:
        name: java-17-amazon-corretto-devel
        state: present
      when: "'amazon' in ansible_os_family"

    - name: Install Git
      package:
        name: git
        state: present

    - name: Install Docker on Ubuntu
      package:
        name: docker.io
        state: present
      when: "'debian' in ansible_os_family"

    - name: Install Maven
      package:
        name: maven
        state: present
