---
- name: Setup SonarQube with Docker and Firewall
  hosts: sonar
  become: true
  tasks:
    - name: Start and Enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create docker-compose.yml file      
      copy:
        content: |
          version: "3"

          services:
            sonarqube:
              image: sonarqube:6.7.1
              container_name: sonarqube
              restart: unless-stopped
              environment:
                - SONARQUBE_JDBC_USERNAME=sonar 
                - SONARQUBE_JDBC_PASSWORD=password123
                - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
              ports:
                - "9000:9000"
                - "9092:9092"
              volumes:
                - sonarqube_conf:/opt/sonarqube/conf
                - sonarqube_data:/opt/sonarqube/data
                - sonarqube_extensions:/opt/sonarqube/extensions
                - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

            db:
              image: postgres:10.1
              container_name: db
              restart: unless-stopped
              environment:
                - POSTGRES_USER=sonar
                - POSTGRES_PASSWORD=password123
                - POSTGRES_DB=sonarqube
              volumes:
                - sonarqube_db:/var/lib/postgresql10
                - postgresql_data:/var/lib/postgresql10/data

          volumes:
            postgresql_data:
            sonarqube_bundled-plugins:
            sonarqube_conf:
            sonarqube_data:
            sonarqube_db:
            sonarqube_extensions:
        dest: /home/ubuntu/docker-compose.yml

    - name: Restart Docker Service
      service:
        name: docker
        state: restarted

    - name: Run docker-compose to bring up SonarQube
      command: docker-compose -f /home/ubuntu/docker-compose.yml up -d

    - name: Install Firewalld
      apt:
        name: firewalld
        state: present
        update_cache: yes

    - name: Start Firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Configure Firewalld to open port 9000
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - http
        - https

    - name: Reload Firewalld
      command: firewall-cmd --reload
